# nanodet-plus-m_320
# COCO mAP(0.5:0.95) = 0.270
#             AP_50  = 0.418
#             AP_75  = 0.281
#           AP_small = 0.083
#               AP_m = 0.278
#               AP_l = 0.451
save_dir: workspace/nanodet-plus-m_ConvNeXt_3333_320X192_DSMhand_smoke3
model:
  weight_averager:
    name: ExpMovingAverager
    decay: 0.9998
  arch:
    name: NanoDetPlus
    detach_epoch: 10
    backbone:
      name: ConvNeXt
      out_stages: [1,2,3]
#    backbone:
#      name: ShuffleNetV2
#      model_size: 1.0x
#      out_stages: [ 2,3,4 ]
#      activation: LeakyReLU
    fpn:
      name: GhostPAN
#      in_channels: [116, 232, 464]
      in_channels: [192, 384, 768]
      out_channels: 96
      kernel_size: 5
      num_extra_level: 1
      use_depthwise: True
      activation: LeakyReLU
    head:
      name: NanoDetPlusHead
      num_classes: 2
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      kernel_size: 5
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
    # Auxiliary head, only use in training time.
    aux_head:
      name: SimpleConvHead
      num_classes: 2
      input_channel: 192
      feat_channels: 192
      stacked_convs: 4
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 7
data:
  train:
    name: CocoDataset
    img_path: /home/chenpengfei/dataset/DSMhand_smoke3/yolov5/images/train
    ann_path: /home/chenpengfei/dataset/DSMhand_smoke3/coco/annotations/train.json
    input_size: [320,192] #[w,h]
    keep_ratio: False
    load_mosaic: 0.0  # 增加mosaic数据增强
    cut_mosaic: 0.0  # 变形版mosaic
    pipeline:
      perspective: 0.0 # 透视or仿射变换
      scale: [0.6, 1.4] # 放缩
      stretch: [[0.8, 1.2], [0.8, 1.2]] # 拉伸
      rotation: 0  # 旋转
      shear: 0  # 裁剪
      translate: 0.2  # 平移
      flip: 0.5  # 左右翻转
      brightness: 0.2  # 亮度
      contrast: [0.6, 1.4]  # 对比度
      saturation: [0.5, 1.2]  # 饱和度
      normalize: [[72.26834, 72.94908, 71.93302], [63.723274, 63.75379, 63.695095]]
  val:
    name: CocoDataset
    img_path: /home/chenpengfei/dataset/DSMhand_smoke3/yolov5/images/val
    ann_path: /home/chenpengfei/dataset/DSMhand_smoke3/coco/annotations/val.json
    input_size: [320,192] #[w,h]
    keep_ratio: False
    pipeline:
      normalize: [[72.26834, 72.94908, 71.93302], [63.723274, 63.75379, 63.695095]]
device:
  gpu_ids: [] # Set like [0, 1, 2, 3] if you have multi-GPUs
  workers_per_gpu: 10
  batchsize_per_gpu: 64
schedule:
#  resume: workspace/nanodet-plus-m_320X192_DSMhand_smoke3_MultiStepLR_280/model_last.ckpt
#  load_model:
  optimizer:
    name: AdamW
    lr: 0.001
    weight_decay: 0.05
  warmup:
    name: linear
    steps: 500
    ratio: 0.0001
  total_epochs: 300
  lr_schedule:
    name: CosineAnnealingLR
    T_max: 300
    eta_min: 0.00005
  val_intervals: 10
grad_clip: 35
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 50

class_names: ['hand', 'cigarette']
